# fly.toml app configuration file generated for projectappoint on 2024-01-29T15:51:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "projectappoint"
primary_region = "waw"

[build]

[env]
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED = "false"
  SPRING_DATASOURCE_URL = "jdbc:postgresql://proappointdb.internal:5432/?user=postgres&password=MXgOlAPIcHsaQHB"
  SPRING_DATASOURCE_USERNAME = "postgres"
  SPRING_LIQUIBASE_URL = "jdbc:postgresql://proappointdb.internal:5432/?user=postgres&password=MXgOlAPIcHsaQHB"
  SPRING_PROFILES_ACTIVE = "prod,api-docs"
  _JAVA_OPTIONS = "-XX:MaxRAM=70m"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
